import dashboards from './dashboards'
import admins from './admins'
import communities from './communities'
import distributionmanagers from './distribution-managers'
import groups from './groups'
import manufacturers from './manufacturers'
import products from './products'
import roles from './roles'
import settings from './settings'
import stations from './stations'
import sales from './sales'
import suppliers from './suppliers'
import users from './users'

export default [...dashboards, ...admins, ...communities, ...distributionmanagers, ...groups, ...manufacturers, ...products, ...roles, ...settings, ...stations, ...sales, ...suppliers, ...users]